POST http://vercel-node-app.pvaisanen.vercel.app/scoreboard
Content-Type: application/json

{
    "name": "Max",
    "category": "0",
    "score": 2,
    "difficulty": "easy"
}

###
GET http://vercel-node-app.pvaisanen.vercel.app/scoreboard/0

###
GET http://localhost:3005/Scoreboard/0
Content-Type: application/json

###
GET http://localhost:3005/Scoreboard/
Content-Type: application/json


###
PATCH http://vercel-node-app.pvaisanen.vercel.app/scoreboard/5fea3218012bd70009839e37
Content-Type: application/json

{
    "name": "Seppo",
    "score": 6
}

###
POST http://vercel-node-app.pvaisanen.vercel.app/login
Content-Type: application/json

{
"username": "Admin123"
}

###
POST Http://localhost:4000/login
Content-Type: application/json

{
"username": "Admin123"
}

###
DELETE http://vercel-node-app.pvaisanen.vercel.app/scoreboard/5feb4fdb1bb9b30008081d87
Content-Type: application/json

