POST http://vercel-node-app.pvaisanen.vercel.app/scoreboard
Content-Type: application/json

{
    "name": "Max",
    "category": "0",
    "score": 2,
    "difficulty": "easy"
}

###
GET http://vercel-node-app.pvaisanen.vercel.app/scoreboard/0

###
GET http://localhost:3005/Scoreboard/0
Content-Type: application/json

###
GET http://localhost:3005/Scoreboard/0/hard
Content-Type: application/json

###
GET http://localhost:3005/Scoreboard/
Content-Type: application/json

###
DELETE http://localhost:3005/scoreboard/5ff4954dbb0b8b670441441c

###
DELETE http://vercel-node-app.pvaisanen.vercel.app/scoreboard/5ff4954dbb0b8b670441441c

###
PATCH http://localhost:3005/scoreboard/5ff4ae492433d000087a7bf1
Content-Type: application/json

{
    "name": "Keijo",
    "score": 3,
    "difficulty": "hard"
}

###
POST http://vercel-node-app.pvaisanen.vercel.app/login
Content-Type: application/json

{
"username": "Admin123"
}

###
POST Http://localhost:4000/login
Content-Type: application/json

{
"username": "Admin123"
}

###
DELETE http://vercel-node-app.pvaisanen.vercel.app/scoreboard/5feb4fdb1bb9b30008081d87
Content-Type: application/json

